#!/usr/bin/env bash
# set -x
set -euo pipefail
cd "`dirname "$0"`/.."

./scripts/dist-ooz
export PATH=$PATH:`pwd`/build/ooz

mkdir -p build/latest
bun_extract_file list-files ./assets/content/depot | grep ".dat64" > build/latest/index.txt
bun_extract_file extract-files --regex ./assets/content/depot build/latest ".*\.dat64$"

# to save space, keep only the language files that differ from english
for lang in `node --eval="require('./scripts/lang.json').map(l => console.log(l))"`; do
  echo "deduping ./build/latest/Data/$lang..."
  for f in `ls ./build/latest/Data/$lang`; do
    diff --brief --ignore-trailing-space "./build/latest/Data/$f" "./build/latest/Data/$lang/$f" >/dev/null && rm "./build/latest/Data/$lang/$f" || true
  done
done
