#!/usr/bin/env bash
# set -x
set -euo pipefail
cd "`dirname "$0"`/.."

ASSETS_EXE_PATH="`pwd`/assets/exe/depot"
ASSETS_PATH="`pwd`/assets/content/depot"
STRINGS_EXE="`pwd`/build/strings/strings.exe"

main() {
  bash ./scripts/dist-s3-versions
  POE_VERSION="`node -e "console.log(require('./dist/s3/versions/latest.json').version)"`"

  dist-netlify "dist/netlify-dev" http://localhost:8000
  dist-netlify "dist/netlify-prod" https://poedat.erosson.org
}

dist-netlify() {
  DIST="$1";shift
  S3_HOSTNAME="$1";shift
  echo dist-netlify $DIST $S3_HOSTNAME

  rm -rf "$DIST"
  mkdir -p "$DIST"
  for VERDIST in `find build/s3-versions/* -type d` `find dist/s3/versions/* -type d || true`; do
    POE_VERSION=`basename "$VERDIST"`
    node ./scripts/dist-netlify-redirects.js "$VERDIST/index.json" "$POE_VERSION" "$S3_HOSTNAME" >> "$DIST/_redirects"
    node ./scripts/dist-netlify-dirindex.js "$VERDIST/index.json" "$POE_VERSION" "$DIST/v"
  done

  # latest version is the last one we processed above. TODO: better logic for this!
  echo "" >> "$DIST/_redirects"
  echo "/latest/*  /v/$POE_VERSION/:splat 302" >> "$DIST/_redirects"
  echo "/v  / 302" >> "$DIST/_redirects"

  node ./scripts/dist-netlify-dirindex-root.js "$DIST"
}

main "$@"
