#!/usr/bin/env bash
# set -x
set -euo pipefail
cd "`dirname "$0"`/.."

mkdir -p build/ooz
PATH=$PATH:./build/ooz

## --location follows redirects
#curl --location https://github.com/erosson/ooz/releases/download/latest/bun_extract_file.exe --output build/ooz/bun_extract_file.exe
#curl --location https://github.com/erosson/ooz/releases/download/latest/libbun.dll --output build/ooz/libbun.dll
#curl --location https://github.com/erosson/ooz/releases/download/latest/ooz.exe --output build/ooz/ooz.exe
#curl --location https://github.com/erosson/ooz/releases/download/latest/libooz.dll --output build/ooz/libooz.dll

mkdir -p build/latest
bun_extract_file list-files ./assets/content/depot | grep ".dat64" > build/latest/index.txt
bun_extract_file extract-files --regex ./assets/content/depot build/latest ".*\.dat64$"

# to save space, keep only the language files that differ from english
for lang in `node --eval="require('./scripts/lang.json').map(l => console.log(l))"`; do
  echo "deduping ./build/latest/Data/$lang..."
  for f in `ls ./build/latest/Data/$lang`; do
    diff --brief --ignore-trailing-space "./build/latest/Data/$f" "./build/latest/Data/$lang/$f" >/dev/null && rm "./build/latest/Data/$lang/$f" || true
  done
done
