#!/usr/bin/env bash
# set -x
set -euo pipefail
cd "`dirname "$0"`/.."

POE_VERSION=`cat ./build/version.txt`
TARGZ="poedat-$POE_VERSION.tar.gz"
rm -rf "dist/$POE_VERSION" dist/latest
mkdir -p dist/latest
cp -r build/latest "dist/$POE_VERSION"
cp build/latest/version* dist/latest
tar -cvzf dist/poedat-latest.tar.gz "dist/$POE_VERSION"
cp dist/poedat-latest.tar.gz "dist/$TARGZ"
cp assets/content/info.txt dist/depot-info.txt
