#!/usr/bin/env bash
# set -x
set -euo pipefail
cd "`dirname "$0"`/.."

ASSETS_EXE_PATH="`pwd`/assets/exe/depot"
ASSETS_PATH="`pwd`/assets/content/depot"
STRINGS_EXE="`pwd`/build/strings/strings.exe"

main() {
  # netlify doesn't have aws installed
  # https://stackoverflow.com/questions/592620/how-can-i-check-if-a-program-exists-from-a-bash-script
  if ! command -v aws; then
    # https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html#cliv2-linux-install
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.0.30.zip" -o build/awscliv2.zip
    unzip build/awscliv2.zip -d build/awscliv2
    mkdir -p build/awscli
    ./build/awscliv2/aws/install --install-dir ./build/awscli/install --bin-dir build/awscli/bin
    PATH=$PATH:`pwd`/build/awscli/bin
    which aws
  fi

  bash ./scripts/dist-s3-versions
  POE_VERSION="`node -e "console.log(require('./dist/s3/versions/latest.json').version)"`"

  dist-netlify "dist/netlify-dev" http://localhost:8000
  dist-netlify "dist/netlify-prod" https://poedat.erosson.org
}

dist-netlify() {
  DIST="$1";shift
  S3_HOSTNAME="$1";shift
  echo dist-netlify $DIST $S3_HOSTNAME

  rm -rf "$DIST"
  mkdir -p "$DIST"
  for VERDIST in `find build/s3-versions/* -type d` `find dist/s3/versions/* -type d || true`; do
    POE_VERSION=`basename "$VERDIST"`
    node ./scripts/dist-netlify-redirects.js "$VERDIST/index.json" "$POE_VERSION" "$S3_HOSTNAME" >> "$DIST/_redirects"
    node ./scripts/dist-netlify-dirindex.js "$VERDIST/index.json" "$POE_VERSION" "$DIST/v"
  done

  # latest version is the last one we processed above. TODO: better logic for this!
  echo "" >> "$DIST/_redirects"
  echo "/latest/*  /v/$POE_VERSION/:splat 302" >> "$DIST/_redirects"
  echo "/v  / 302" >> "$DIST/_redirects"

  node ./scripts/dist-netlify-dirindex-root.js "$DIST"
}

main "$@"
