#!/usr/bin/env bash
# set -x
set -euo pipefail
cd "`dirname "$0"`/.."

./scripts/dist-ooz
(cd third-party/PyPoE && pip install -e .[cli-full])

export POE_VERSION="`cat build/version.txt`"
export ASSETS_PATH="`pwd`/assets/content/depot"
export PYPOE_TARGET="`pwd`/build/pypoe/pypoe-$POE_VERSION.min.json"
mkdir -p build/pypoe/

cd build/ooz # pypoe insists on having libooz.dll in the current directory
pypoe_exporter config set ggpk_path $ASSETS_PATH
pypoe_exporter dat json "$PYPOE_TARGET"
cd -
node ./scripts/dist-pypoe-split.js "$PYPOE_TARGET" build/pypoe/dat
