#!/usr/bin/env bash
# set -x
set -euo pipefail
cd "`dirname "$0"`/.."

ASSETS_EXE_PATH="./assets/exe/depot"
STRINGS_EXE="./build/strings/strings.exe"
mkdir -p build/strings
[ ! -f "$STRINGS_EXE" ] && unzip third-party/Strings.zip -d build/strings
"$STRINGS_EXE" -accepteula 2>/dev/null || true

mkdir -p build/latest
POE_VERSION="`"$STRINGS_EXE" "$ASSETS_EXE_PATH/PathOfExileSteam.exe" | grep release/tags/ | sed -e "s_release/tags/__"`"
if [ -z $POE_VERSION ]; then
  echo "Failed to find poe version"
  exit 1
fi
echo "${POE_VERSION}" | tee build/version.txt | tee "build/latest/version.txt"
echo "{\"version\":\"${POE_VERSION}\"}" > "build/latest/version.json"
