#!/usr/bin/env bash
# set -x
set -euo pipefail
cd "`dirname "$0"`/.."

# S3 doesn't have a builtin way to do directory listings, so generate static listings
# https://stackoverflow.com/a/46383157/2782048
# http://gnuwin32.sourceforge.net/packages/tree.htm
TREE="`pwd`/third-party/tree/bin/tree"
TMP="`pwd`/build/tmp-index.html"
[ ! -f "$TREE" ] && unzip third-party/tree-*-bin.zip -d build/tree
for d in `find dist -type d`; do
  cd $d
  rm -f ./index.html
  $TREE -H . -L 1 --noreport --charset utf-8 > $TMP
  mv $TMP ./index.html
  cd -
done
