#!/usr/bin/env bash
# set -x
set -euo pipefail
cd "`dirname "$0"`/.."

rm -rf build/s3-versions dist/s3/versions.json dist/s3/versions.min.json
aws s3 sync --no-sign-request s3://poedat.erosson.org/versions/ build/s3-versions
if [ -f build/latest/version.json ]; then
  # local dev run, after an s3 build
  mkdir -p dist/s3/versions
  cp build/latest/version.json dist/s3/versions/latest.json
  node ./scripts/dist-s3-versions.js
else
  # netlify ci run, use what's on s3
  mkdir -p dist/s3
  cp -rp build/s3-versions dist/s3/versions
fi
