#!/usr/bin/env bash
# set -x
set -euo pipefail
cd "`dirname "$0"`/.."

cp third-party/s3-bucket-listing/index.html third-party/s3-bucket-listing/list.js dist/
cp third-party/s3-bucket-listing/index.html dist/error.html
