#!/usr/bin/env bash
# set -x
set -euo pipefail
cd "`dirname "$0"`/.."


case "`uname -s`" in
    Linux*)
        pip install -r third-party/steampull/requirements.txt
        ;;
    Darwin*)
        # no idea if mac works, untested
        pip install -r third-party/steampull/requirements.txt
        ;;
    *)
        pip install -r third-party/steampull/requirements-win.txt
        ;;
esac
[ -f auth.env ] && . auth.env ; ./third-party/steampull/steampull auth
