#!/usr/bin/env node
const fs = require("fs")
const path = require("path")
const promisify = require("util").promisify
const child_process = require("child_process")
const S3 = require("@aws-sdk/client-s3")
const minimist = require("minimist")
const tmp = require("tmp-promise")
const glob = require("glob")

async function main() {
  const args = await parseArgs(process.argv.slice(2))
  const s3 = new S3.S3Client({region: 'us-east-1'})

  // pull tree, build dirindex, push tree
  await runSync(`s3://${args.bucket}/${args.prefix}${args.tree || ''}`, args.build)

  console.log("building index.json...")
  const indexFiles = (await promisify(glob.glob)(args.build+'/**', {nodir: true}))
    .map(f => path.relative(args.build, f).replace(/\\/g, '/'))
    // ignore files generated by this script, if necessary
    .filter(f => args.tree || (f !== "index.json" && f !== "index.html"))
  if (!indexFiles.length) {
    throw new Error("empty dirindex")
  }

  console.log(`pushing index.json - ${indexFiles.length} files...`)
  if (!args.dryrun) {
    await s3.send(new S3.PutObjectCommand({
      Bucket: args.bucket,
      Key: `${args.prefix}index.json`,
      ContentType: "application/json",
      Body: JSON.stringify(indexFiles),
    }))
  }

  console.log("building index.html...")
  const indexHtml = (await fs.promises.readFile(path.join(__dirname, 's3dirindex-template.html')))
    .toString()
    .replace(/\{\{\$LIST\}\}/g, indexFiles
      .map(f => `    <li><a href="${args.tree || '.'}/${f}">${f}</a></li>`)
      .join("\n")
    )
  console.log("pushing index.html...")
  if (!args.dryrun) {
    await s3.send(new S3.PutObjectCommand({
      Bucket: args.bucket,
      Key: `${args.prefix}index.html`,
      ContentType: "text/html",
      Body: indexHtml,
    }))
  }

  console.log(`https://s3.amazonaws.com/${args.bucket}/${args.prefix}index.html`)
}

async function runSync(src, dest, args=[]) {
  return new Promise((resolve, reject) => {
    console.log(`sync: ${src} --> ${dest}`)
    const p = child_process.spawn("aws", ["s3", "sync", src, dest].concat(args))
    p.stdout.on('data', data => console.log(`${data}`))
    p.stderr.on('data', data => console.error(`${data}`))
    p.on('close', code => {
      if (code) {
        return reject(`aws s3 sync failure: ${code}`)
      }
      return resolve()
    })
  })
}

async function parseArgs(argv) {
  const args = minimist(argv)
  if (!args.bucket || !args.prefix) {
    console.error(`usage: node s3dirindex.js --bucket BUCKET --prefix PREFIX [--tree TREE_PREFIX] [--build BUILD_DIR]`)
    process.exit(1)
  }
  const {bucket, tree, dryrun} = args
  const prefix = args.prefix || '/'
  if (prefix && !prefix.endsWith('/')) throw new Error('--prefix must end with "/"')
  const build = await getBuildDir(args)
  return {prefix, bucket, tree, build, dryrun}
}

async function getBuildDir(args) {
  if (args.build) {
    await fs.promises.rmdir(args.build, {recursive: true})
    await fs.promises.mkdir(args.build, {recursive: true})
    return args.build
  }
  else {
    const d = await tmp.dir({unsafeCleanup: true})
    return d.path
  }
}

main().catch(err => {
  console.error(err)
  process.exit(1)
})
