name: web-and-wiki
on:
  schedule:
   - cron: "20 0 * * *"
  workflow_dispatch:

jobs:
  distpush:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install --frozen-lockfile

      - env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: yarn distpush:web && yarn distpush:wiki && yarn distpush:root

      #- if: ${{ env.STEAM_DEPOT_INFO_DIFF != '' }}
      #  uses: "marvinpinto/action-automatic-releases@latest"
      #  with:
      #    repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #    automatic_release_tag: "latest-web"
      #    prerelease: true
      #    title: "Latest Web Build"
      #    files: |
      #      build/web/*
